server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: mesync-cloud
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
app:
  registration:
    invite-ttl: 10m
    invite-cooldown: 10s
    nonce-ttl: 30s
    rate-limit-ttl: 10m
    attempts: 10
  auth:
    nonce-ttl: 30s
    rate-limit-ttl: 60s
    attempts: 120
  revoke:
    ttl: 30d
  cache:
    ttl: 12h
    user-cache-size: 40_000
    device-cache-size: 100_000
logging:
  pattern:
    level: >-
      %5p
      requestId=%X{requestId:-}
      method=%X{method:-}
      path=%X{path:-}
      jwtAuthId=%X{jwtAuthId:-}
      userAuthId=%X{userAuthId:-}
      devicePublicId=%X{devicePublicId:-}