-- V1__init_users_devices

-- users table
CREATE TABLE IF NOT EXISTS users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_sub UUID        NOT NULL UNIQUE,
    email        TEXT                 DEFAULT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_keycloak_sub ON users (keycloak_sub);

CREATE OR REPLACE FUNCTION autoupdate_users_updated_at() RETURNS TRIGGER
    LANGUAGE plpgsql AS
$$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER autoupdate_users_updated_at_trigger
    BEFORE UPDATE
    ON users
    FOR EACH ROW
EXECUTE FUNCTION autoupdate_users_updated_at();

-- devices table
CREATE TABLE IF NOT EXISTS devices
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id      UUID        NOT NULL UNIQUE,
    user_id        BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    device_type    TEXT        NOT NULL CHECK (device_type IN ('MOBILE', 'BROWSER', 'DESKTOP')),
    name           TEXT        NOT NULL,

    public_key              BYTEA NOT NULL UNIQUE CHECK (length(public_key) = 44),
    key_created_at          TIMESTAMPTZ NULL,

    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at   TIMESTAMPTZ NOT NULL,
    revoked_at     TIMESTAMPTZ NULL,

    extras         JSONB       NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT uq_devices_user_id_name UNIQUE (user_id, name)
);

CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices (user_id);
CREATE INDEX IF NOT EXISTS idx_devices_user_active ON devices (user_id) WHERE revoked_at IS NULL;

CREATE OR REPLACE FUNCTION autoupdate_devices_updated_at() RETURNS TRIGGER
    LANGUAGE plpgsql AS
$$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER autoupdate_devices_updated_at_trigger
    BEFORE UPDATE
    ON devices
    FOR EACH ROW
EXECUTE FUNCTION autoupdate_devices_updated_at();
