-- V1__init_users_devices

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_sub    UUID NOT NULL UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS devices (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_type     TEXT NOT NULL CHECK ( device_type IN ('mobile', 'browser', 'desktop') ),
    name            TEXT NOT NULL,

    public_key_pem          TEXT NULL,
    public_key_algorithm    TEXT NULL,
    key_created_at          TIMESTAMPTZ NULL,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at      TIMESTAMPTZ NULL,

    extras          JSONB NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT uq_devices_user_id_name UNIQUE (user_id, name)
);

CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);
CREATE INDEX IF NOT EXISTS idx_devices_user_active ON devices(user_id) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_devices_last_seen ON devices(last_seen_at);

