-- V6__create_message_and_sms_message

CREATE TABLE IF NOT EXISTS messages
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    device_id    BIGINT      REFERENCES devices (id) ON DELETE SET NULL,
    address      TEXT        NOT NULL,
    key_version  INTEGER     NOT NULL,
    message_type TEXT        NOT NULL CHECK (message_type IN ('SMS')),
    direction    TEXT        NOT NULL CHECK (direction in ('INCOMING', 'OUTGOING')),
    occurred_at  TIMESTAMPTZ NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    ciphertext   BYTEA       NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_user_id_id ON messages (user_id, id);